#pragma once
#include "problem_08_01_tripleStep.h"
#include "problem_08_02_robotGrid.h"
#include "problem_08_03_magicIndex.h"
#include "problem_08_04_powerSet.h"
#include "problem_08_05_recursiveMultiply.h"
#include "problem_08_07_permutationsNoDups.h"
#include "problem_08_08_permutationsWithDups.h"
#include "problem_08_10_paintFill.h"
